<?xml version="1.0"?>
<section xml:id="exceptions_principles-for-using-exceptions">
  <title>Principles for using Exceptions</title>
  <p>There are many bad examples of <em>exception</em> use on the Internet. The purpose
            of an <em>exception</em> is to modify the flow-of-control, not to catch simple errors.
            If your <c>try: except:</c> block is in the same function that <c>raises</c> the
            exception, you are probably mis-using exceptions.</p>
  <topic>
    <title>Principle 1:</title>
    <p>If a condition can be handled using the normal flow-of-control, don't
                use an exception!</p>
  </topic>
  <p>Example 1:</p>
  <table>
    <tabular>
      <row>
        <cell><term>DON'T DO THIS</term>:
                        </cell>
        <cell>
                            When you can just as easily test for no
                                items in the list doing this:
                        </cell>
      </row>
      <row>
        <cell>
          <program language="Python">
            <code>
try:
  average = sum(a_list) / len(a_list)
except ZeroDivisionError:
  average = 0
</code>
          </program>
        </cell>
        <cell>
          <program language="Python">
            <code>
if len(a_list) &gt; 0:
  average = sum(a_list) / len(a_list)
else:
  average = 0
</code>
          </program>
        </cell>
      </row>
    </tabular>
  </table>
  <p>Example 2:</p>
  <table>
    <tabular>
      <row>
        <cell><term>DON'T DO THIS</term>:
                        </cell>
        <cell>
                            When you can just as easily test for a
                                valid index doing this:
                        </cell>
      </row>
      <row>
        <cell>
          <program language="Python">
            <code>
try:
  value = my_list[index]
except IndexError:
  value = -1
</code>
          </program>
        </cell>
        <cell>
          <program language="Python">
            <code>
if 0 &lt;= index &lt; len(my_list):
  value = my_list[index]
else:
  value = -1
</code>
          </program>
        </cell>
      </row>
    </tabular>
  </table>
  <p>Example 3:</p>
  <table>
    <tabular>
      <row>
        <cell><term>DON'T DO THIS</term>:
                        </cell>
        <cell>
                            When you can just as easily test
                                to see if the key is valid doing this:
                        </cell>
      </row>
      <row>
        <cell>
          <program language="Python">
            <code>
try:
  value = my_dictionary[key]
except KeyError:
  value = -1
</code>
          </program>
        </cell>
        <cell>
          <program language="Python">
            <code>
if key in my_dictionary.keys():
  value = my_dictionary[key]
else:
  value = -1
</code>
          </program>
        </cell>
      </row>
    </tabular>
  </table>
  <topic>
    <title>Principle 2:</title>
    <p>If you call a function that potentially raises exceptions, and you can do
                something appropriate to deal with the exception, then surround the code
                that contains the function call with a <c>try: except:</c> block.</p>
  </topic>
  <p>Example: Suppose you have a function that reads a file to set the state of
            an application when it starts up. You should catch any errors related to
            reading the file and set the state of the application to default values if
            they can't be set from the file.</p>
  <program language="Python">
    <code>
try:
  load_state('previous_state.txt')
except OSError:
  set_state_to_defaults()
</code>
  </program>
  <topic>
    <title>Principle 3:</title>
    <p>If you call a function that potentially raises exceptions, and you can't do
                anything meaningful about the conditions that are raised, then don't
                catch the exception message(s).</p>
  </topic>
</section>
